[package]
name = "tuid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
chrono = ["dep:chrono"]

[dependencies]
chrono = { version = "0.4.23", optional = true }
